name: Run Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '00 11 * * 6,1,3,5'
env:
  TOKEN: '${{ secrets.TOKEN }}'
  ID: '${{ secrets.ID }}'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 7.26.2
      - run: pnpm install
      - run: pnpm dev:run
